version: 0.2

env:
  parameter-store:
    AWS_ACCOUNT_ID: /myapp/aws-account-id
    AWS_REGION: /myapp/aws-region
    ECR_REPOSITORY_NAME: /myapp/ecr-repository/name

phases:
  install:
    runtime-versions:
      nodejs: 12.2.0
    commands:
      - echo Installing Node.js and npm...
      - n 12.2.0
      - npm config set registry https://registry.npmjs.org/

  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      # update the following line with your own region
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME
      - echo ECR Image Name: $REPOSITORY_URI:$IMAGE_TAG
      - echo Checking out aws-cicd branch...
      - git checkout aws-cicd

  build:
    commands:
      - echo Build started on `date`
      - echo Packaging application into a zip file...
      - zip -r online_shop.zip * .[^.]*
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - docker images
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Uploading zip file to S3 root location...
      - aws s3 cp online_shop.zip s3://my-codepipeline-artifacts-03/online-shop/
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s", "Port":8000}' $REPOSITORY_URI:$IMAGE_TAG > imageDefinitions.json
      - cat imageDefinitions.json

artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no
  exclude-patterns:
    - 'node_modules/**/*'
    - '.git/**/*'
    - '.gitignore'
    - 'README.md'
    - 'package-lock.json'
